Repository habx/lib-form-helper, pull requests merged in 2021-02, with the labels that each got.

#578 Revert "Update dependency husky to v5"
  package.json
Labels: habx-automerge

#579 APP-18811: Label should be ReactNode instead of strings
  src/useFinalFormField/useFinalFormField.interface.ts
  src/useFinalFormField/useFinalFormField.tsx
Labels: habx-automerge, habx-autorelease

#580 Syncing dev with v7.0.1
  src/useFinalFormField/useFinalFormField.interface.ts
  src/useFinalFormField/useFinalFormField.tsx
Labels: habx-automerge

#582 Syncing dev with v7.0.2
  src/useFinalFormField/useFinalFormField.tsx
Labels: habx-automerge

#586 APP-18923: Try fixing infinite loading of the `CodeEditorJSON` component
  src/fields/CodeEditorJSON/CodeEditorJSON.tsx
  src/fields/CodeEditorJSON/index.ts
Labels: habx-autorelease

#587 Syncing dev with v7.0.3
  src/fields/CodeEditorJSON/CodeEditorJSON.tsx
  src/fields/CodeEditorJSON/index.ts
Labels: habx-automerge

#601 APP-16391: Fix CircleCI context
  .circleci/config.yml
Labels: habx-automerge
