Repository habx/lib-form-helper, pull requests merged in 2021-06, with the labels that each got.

#680 APP-20160: usePreventLeaveDecorator
  package-lock.json
  package.json
  src/Form/Form.messages.ts
  src/decorators/useFormAutoSubmitDecorator/index.ts
  src/decorators/useFormAutoSubmitDecorator/useFormAutoSubmitDecorator.ts
  src/decorators/useFormKeyboardSubmitDecorator/index.ts
  src/decorators/useFormKeyboardSubmitDecorator/useFormKeyboardSubmitDecorator.ts
  src/decorators/usePreventLeaveDecorator/index.ts
  src/decorators/usePreventLeaveDecorator/usePreventLeaveDecorator.ts
  src/index.ts
Labels: automerge, autorelease

#685 APP-21576: Fix intl
  src/Form/Form.messages.ts
  src/decorators/usePreventLeaveDecorator/index.ts
  src/decorators/usePreventLeaveDecorator/usePreventLeaveDecorator.ts
  src/index.ts
Labels: automerge, autorelease

#686 Syncing dev with v7.3.1
  src/Form/Form.messages.ts
  src/decorators/usePreventLeaveDecorator/index.ts
  src/decorators/usePreventLeaveDecorator/usePreventLeaveDecorator.ts
  src/index.ts
Labels: automerge

#707 APP-22189: Prevent errors from being partially hidden
  src/FieldError/FieldError.tsx
Labels: autorelease

#710 APP-22176: Fix typo
  src/Form/Form.messages.ts
Labels: autorelease
